import { EventEmitter, OnDestroy, OnInit, ElementRef, Type, Injector } from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { ConnectionStatus } from '../../services/lora-client.service';
import { ClientMessage } from "../../types/ClientMessage";
import * as i0 from "@angular/core";
export declare class LoraClient implements OnInit, OnDestroy {
    private el;
    private sanitizer;
    token: string;
    height: number;
    stylesFile: string;
    partsTableComponent: Type<any> | null;
    onMessage: EventEmitter<ClientMessage>;
    messages: ClientMessage[];
    message: string;
    status: ConnectionStatus;
    sanitizedStylesFile: SafeResourceUrl;
    protected readonly ConnectionStatus: typeof ConnectionStatus;
    private onMessageListener;
    private onStatusListener;
    private loraClientService;
    constructor(el: ElementRef, sanitizer: DomSanitizer);
    ngOnInit(): void;
    connect(): Promise<void>;
    createInjector(): Injector;
    sendMessage(): void;
    onMessageChanged(message: string): void;
    onEnterPressed(): void;
    onClickReconnect(): void;
    onMessageReceived(message: ClientMessage): void;
    onStatus(status: ConnectionStatus): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<LoraClient, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<LoraClient, "lora-client", never, { "token": { "alias": "token"; "required": false; }; "height": { "alias": "height"; "required": false; }; "stylesFile": { "alias": "stylesFile"; "required": false; }; "partsTableComponent": { "alias": "partsTableComponent"; "required": false; }; }, { "onMessage": "onMessage"; }, never, never, true, never>;
}
